name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./docker/build.sh

    - name: Upload image as artifact
      uses: actions/upload-artifact@v2
      with:
          name: dockerproject
          path: /tmp/dockerproject.tar
          retention-days: 7

    - name: Check
      run: md5sum /tmp/dockerproject.tar

  make:
    needs: build-docker
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts (Docker images) from previous workflows
      uses: actions/download-artifact@v2
      with:
        name: dockerproject
        path: /tmp

    - name: Check
      run: md5sum /tmp/dockerproject.tar

    - name: Load Docker image
      run: docker import /tmp/dockerproject.tar dockerproject-image:latest

    - name: Docker ls
      run: docker image ls

    - uses: actions/checkout@v3
    - name: Make C code
      run: ./docker/run.sh make -C ./c

    - name: Test heaps
      run: ./c/GenericHeaps/obj/test
